global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   map_type: costmap
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   transform_tolerance: 0.5
#   plugins:

#        - {name: structural_objects, type: "semantic_costmap::StructuralObjectsLayer"}
#        - {name: heavy_objects, type: "semantic_costmap::HeavyObjectsLayer"}
#        - {name: light_objects, type: "semantic_costmap::LightObjectsLayer"}



  
