controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.05
  max_vel_theta: 0.2
  min_vel_theta: -0.2
  #max_rotational_vel: 1.5
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 3.2
  acc_lim_x: 1.2
  acc_lim_y: 1.8

  holonomic_robot: false
#  yaw_goal_tolerance: 0.2
#  xy_goal_tolerance: 0.3
  goal_distance_bias: 5.0
  pdist_scale: 5.0
  sim_time: 1.9
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.25

  vx_samples: 9
  vtheta_samples: 35
  dwa: false

