global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   map_type: costmap
   update_frequency: 10.0
   publish_frequency: 10.0
   static_map: true
   transform_tolerance: 0.5
#   plugins:
#        - {name: structural_objects, type: "semantic_costmap::StructuralObjectsLayer"}
#        - {name: heavy_objects, type: "semantic_costmap::HeavyObjectsLayer"}
#        - {name: light_objects, type: "semantic_costmap::LightObjectsLayer"}
#        - {name: stactic_layer,     type: "costmap_2d::StaticLayer"}
#        - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
#        - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
#   publish_frequency: 1.0
#   obstacle_layer:
#       observation_sources: laser_scan_sensor
#       laser_scan_sensor: {data_type: LaserScan, sensor_frame: /lms100, clearing: true, marking: true, topic: /scan}


  
